Added responsive Navbar / favicon / main container
JustinoTorreblanca/dooper-bootcamp pull request #3
Opened 2022-04-07 18:20 UTC by JustinoTorreblanca

https://linear.app/dooper/issue/BOO-13/13-create-layout

2022-04-08 01:33 UTC, ferpintado requested changes

2022-04-08 01:33 UTC, ferpintado commented on src/components/Header/Header.tsx
> +        <ThemeProvider theme={theme}>
ThemeProvider debe ser definido solamente una vez, idealmente en `_app.tsx`

2022-04-08 01:33 UTC, ferpintado commented on src/components/Header/Header.tsx
> +          <Button color="inherit">
Me da curiosidad por que el valor de `color` es `inherit`? Que color se espera?

2022-04-08 01:33 UTC, ferpintado commented on src/components/Header/Header.tsx
> +                <Styles.CustomButton color="inherit">
Para evitar tanta repeticion y hacerlo mas modular y dinamico, sugeriria que pusieras los valores de cada menu en un array y hicieras un `.map`. De esta manera solamente tendras que hacer cambios a un solo elemento en vez de todos manualmente.

2022-04-08 01:33 UTC, ferpintado commented on src/components/Header/styles.tsx
> +  background-color: #fff;
Es recomendable usar los colores definidos en el tema i.e. `props.theme.palette.white`

2022-04-08 01:33 UTC, ferpintado commented on src/components/Header/styles.tsx
> +  :hover {
Es buena practica dejar un espacio entre definiciones para que sea mas facil su lectura

2022-04-08 01:33 UTC, ferpintado commented on src/components/Header/styles.tsx
> +  background-image: url("/_next/image?url=%2Fassets%2Flogo-dooper.png&w=384&q=75");
Todos los archivos que estan en assets puedes referenciarlos directamente de la misma manera `/assets/logo_dooper.png` https://nextjs.org/learn/basics/assets-metadata-css/assets .

2022-04-08 01:33 UTC, ferpintado commented on src/components/MainContainer/MainContainer.tsx
> +    <ThemeProvider theme={theme}>
Nuevamente, theme provider solamente se usa una vez en un top-level component. Todos los componentes dentro de el adaptaran ese tema

2022-04-08 01:33 UTC, ferpintado commented on src/components/Layout/Layout.tsx
> +      {/* <Box>{children}</Box> */}
Borrar elementos si no es necesario

2022-04-08 01:33 UTC, ferpintado commented on src/components/Layout/styles.tsx
> +export const Element = styled(Box)<LayoutProps>`
Llamar variables con un nombre significativo, por ejemplo. `LayoutWrapper`.

2022-04-08 01:33 UTC, ferpintado commented on src/components/Layout/styles.tsx
> +export type LayoutProps = { children?: React.ReactNode | HTMLElement };
No es necesario este type porque `children` no esta siendo usado dentro del styled component

2022-04-08 01:40 UTC, JustinoTorreblanca commented on src/components/Header/Header.tsx
> +          <Button color="inherit">
Tienes razón, no tiene sentido... lo copie de un componente de MUI, enseguida lo quito

2022-04-08 16:51 UTC, stobar93 reviewed
En general se ve buen trabajo. Solamente haría un poco más modular el componente Header, para que a futuro te sea más fácil mantener el código y también sea más fácil de entender

2022-04-08 16:51 UTC, stobar93 commented on pages/register.tsx
> +    <MainContainer>
Este componente podrías ponerlo en Layout directamente, así no necesitas repetirlo en cada pagina

2022-04-08 16:51 UTC, stobar93 commented on pages/profile.tsx
> +    <MainContainer>
Igual aqui

2022-04-08 16:51 UTC, stobar93 commented on pages/index.tsx
> +        <MainContainer>
Aquí también

2022-04-08 16:51 UTC, stobar93 commented on src/components/Header/Header.tsx
> +        <Hidden mdDown>
Interesante. No había probado este componente de MUI pero busque en la documentación que hace, y resulta que está deprecated. Podrías usar un Hook de MUI useMediaQuery para lo que necesites hacer responsive

2022-04-08 16:53 UTC, ferpintado commented on src/components/Header/Header.tsx
> +        <Hidden mdDown>
@JustinoTorreblanca Como alternativa tambien podrias usar  `<Box display={{xs: 'hidden': md: 'block'}}>`

2022-04-11 17:59 UTC, ferpintado approved these changes
Se ve bien, solo unas pequeñas sugerencias. Me gustó como fue mejorando gracias a los feedbacks

2022-04-11 17:59 UTC, ferpintado commented on src/components/Header/components/DesktopMenu/DesktopMenu.tsx
> +    <Box>
Creo que tener dos <Box> es redundante en este caso.

2022-04-11 17:59 UTC, ferpintado commented on pages/index.tsx
> +          src="/_next/image?url=%2Fassets%2Flogo-dooper.png&w=384&q=75"
recuerda hacer referencia a `/assets/` directamente

2022-04-11 18:07 UTC, JustinoTorreblanca commented on pages/index.tsx
> +          src="/_next/image?url=%2Fassets%2Flogo-dooper.png&w=384&q=75"
Cierto, me falto actualizar esta referencia.

2022-04-11 18:08 UTC, merged