Added Login / Register / Profile UI
JustinoTorreblanca/dooper-bootcamp pull request #4
Opened 2022-04-18 14:20 UTC by JustinoTorreblanca

https://linear.app/dooper/issue/BOO-16/14-auth-components

2022-04-18 15:29 UTC, ferpintado requested changes

2022-04-18 15:29 UTC, ferpintado commented on src/components/Auth/components/Login/Login.tsx
> +    .min(6, "Pocos caracteres")
Recomiendo darle un feedback mas exacto al usuario. "Nombre de usuario debe ser minimo 6 caracteres"

2022-04-18 15:29 UTC, ferpintado commented on src/components/Auth/components/Login/Login.tsx
> +    .required("Username is required"),
Dejar los mensajes de error en un solo idioma

2022-04-18 15:29 UTC, ferpintado commented on src/components/Auth/components/Login/Login.tsx
> +          /* helperText={formik.errors.user}
borrar codigo comentado si no se necesita, aunque `helperText` es buena opcion para mostrar los errores

2022-04-18 15:29 UTC, ferpintado commented on src/components/Auth/components/Login/Login.tsx
> +  console.log(formik);
Borrar console logs antes de hacer commit para mantener el codigo y consola limpia

2022-04-18 15:29 UTC, ferpintado commented on src/components/Auth/components/Login/styles.tsx
> +export const Element = styled(Box)`
Note que este elemento va "brincando" de tamaño conforme vas escribiendo en los campos. Quizá sea buena opción tener un width fijo para evitar eso

2022-04-18 15:29 UTC, ferpintado commented on src/components/Auth/components/Profile/Profile.tsx
> +  console.log(userProfile);
Igual, borrar console log para mantener codigo limpio

2022-04-18 15:29 UTC, ferpintado commented on src/components/Auth/components/Register/Register.tsx
> +  name: Yup.string()
Mismos comentarios que el componente Login

2022-04-18 15:29 UTC, ferpintado commented on src/components/Header/components/components/HeaderLogo/HeaderLogo.tsx
> +import React from "react";
Hay como 3 elementos HeaderLogo o parecidos

2022-04-18 15:47 UTC, stobar93 requested changes

2022-04-18 15:47 UTC, stobar93 commented on pages/home.tsx
> +    <MainContainer>
Me parece que esto se repite en la pagina index. Es necesario?

2022-04-18 15:47 UTC, stobar93 commented on src/components/Auth/components/Login/Login.tsx
> +          /* helperText={formik.errors.user}
```suggestion
          helperText={formik.errors && formik.errors.username }
```
Puedes aprovechar mas lo que trae por defecto MUI para mostrar el feedback al usuario

2022-04-18 15:47 UTC, stobar93 commented on src/components/Auth/components/Profile/Profile.tsx
> +  console.log(userProfile);
```suggestion

```

2022-04-18 15:47 UTC, stobar93 commented on src/components/Auth/components/Profile/Profile.tsx
> +        color="thertiary"
```suggestion
        color="tertiary"
```

2022-04-18 15:47 UTC, stobar93 commented on src/components/Auth/components/Register/Register.tsx
> +      createdOn: new Date()
Pienso que si no requieres este valor en otra parte lo puedes quitar. Supabase lo setea automaticamente

2022-04-18 15:47 UTC, stobar93 commented on src/components/Header/components/LogoHeader/LogoHeader.tsx
> +type LogoHeaderProps = {};
```suggestion

```

2022-04-18 15:47 UTC, stobar93 commented on src/components/Header/components/components/LogoHeader/LogoHeader.tsx
> +export default LogoHeader;
Revisa la ruta de este componente. Me parece que lo tienes duplicado con estos: 
[src/components/Header/components/components/HeaderLogo/HeaderLogo.tsx](https://github.com/JustinoTorreblanca/dooper-bootcamp/blob/c4c46c110956ea134b12e36f10beedc5ef02495b/src/components/Header/components/components/HeaderLogo/HeaderLogo.tsx)

[src/components/Header/components/LogoHeader/LogoHeader.tsx](https://github.com/JustinoTorreblanca/dooper-bootcamp/blob/c4c46c110956ea134b12e36f10beedc5ef02495b/src/components/Header/components/LogoHeader/LogoHeader.tsx)

2022-04-19 00:50 UTC, ferpintado approved these changes

2022-04-19 03:52 UTC, merged