FEATURE: connect supabase auth, auth context, login, register, edit p…
JustinoTorreblanca/dooper-bootcamp pull request #5
Opened 2022-04-25 20:23 UTC by JustinoTorreblanca

https://linear.app/dooper/issue/BOO-20/15-connect-supabase-auth

PR, tengo un tema con los buttons de login y register, si los wrappeo en un Link de next, no sirve la validación del formulario y redirige a la pagina, por eso los deje comentados, mientras encuentro otra solución. Por lo tanto, si quieren entrar a /profile, hay que navegar por el menu o directamente en la url.

2022-04-26 16:35 UTC, ferpintado requested changes

2022-04-26 16:35 UTC, ferpintado commented on src/components/Auth/components/Login/Login.tsx
> +  };
Aqui es donde necesitas hacer la redireccion hacia el perfil, no en el boton, una vez que supabase nos regrese el objecto `user` ahi podremos validar que el usuario ha sido identificado y por medio de un `router.push('/profile'` podemos redirigir al usuario.

2022-04-26 16:35 UTC, ferpintado commented on src/components/Auth/components/Register/Register.tsx
> +    user ? setUserRegistered(userRegistered) : null;
una vez que el usuario ha sido registrado tenemos que crear el perfil dentro de la tabla profiles, recuerda que `auth.user` es solamente la identidad con la que se identifica el usuario y se relaciona dentro de la base de datos con las otras tablas. 

Se puede hacer de dos maneras:
- Crear manualmente el row en la base de datos `supabase.from('profiles').insert(......)` 
- Ejecutar un trigger, que es una funcion dentro de la base de datos, que se ejecuta despues de un evento, en este caso es la insercion
https://database.dev/handle-new-user

2022-04-26 16:35 UTC, ferpintado commented on src/components/Header/components/components/HeaderLogo/HeaderLogo.tsx
> +import React from "react";
Creo que este archivo no se necesita

2022-04-26 16:35 UTC, ferpintado commented on src/components/Header/components/components/LogoHeader/LogoHeader.tsx
> +import React from "react";
Creo que este archivo no se necesita

2022-04-26 16:35 UTC, ferpintado commented on src/utils/PrivateComponent.tsx
> +  useEffect(() => {
esto parece estar haciendo lo mismo que en `useAuth`, es necesario tenerlo aqui tambien? aparentemente es el mismo valor de `session`

2022-04-27 03:52 UTC, ferpintado requested changes

2022-04-27 03:52 UTC, ferpintado commented on src/components/Auth/components/Login/Login.tsx
> +      //Mostrar spinner o loading
falto por implementar

2022-04-27 03:52 UTC, ferpintado commented on src/components/Auth/components/Profile/Profile.tsx
> +      //mostrar algo al usuario
no implementado

2022-04-27 03:52 UTC, ferpintado commented on src/components/Auth/components/Profile/Profile.tsx
> +    console.log({ values });
eliminar para mantener codigo limpio

2022-04-27 03:52 UTC, ferpintado commented on src/components/Auth/components/Profile/Profile.tsx
> +      //mostrar algo al usuario
no implementado

2022-04-27 03:52 UTC, ferpintado commented on src/components/Auth/components/Profile/Profile.tsx
> +    // mostrar feedback al usuario
falto por implementar

2022-04-27 03:52 UTC, ferpintado commented on src/components/Auth/components/Profile/Profile.tsx
> +    //validationSchema: ValidateFormSchema,
formulario necesita ser validado

2022-04-27 03:52 UTC, ferpintado commented on src/components/Auth/components/Register/Register.tsx
>          //redirectTo: (window.location.href = redirectToProfile)
eliminar si no es necesario

2022-04-28 22:10 UTC, stobar93 requested changes

2022-04-28 22:10 UTC, stobar93 commented on pages/index.tsx
> +        {!session && (
Si no hay una sesión se muestra el contenido y cuando hay una sesión activa, que muestras?

2022-04-28 22:10 UTC, stobar93 commented on src/components/Auth/components/Login/Login.tsx
> +  email: Yup.string()
Yup tiene el método email con el que puedes validar que tenga la estructura de un email
```suggestion
  email: Yup.string().email()
```

2022-04-28 22:10 UTC, stobar93 commented on pages/index.tsx
> +        {!session && (
Cuando no hay una sesión activa que contenido se muestra al usuario?

2022-04-28 22:10 UTC, stobar93 commented on src/components/Auth/components/Login/Login.tsx
>      .min(5, "Username must have min 5 characters")
```suggestion
    .min(5, "email must have min 5 characters")
```

2022-04-28 22:10 UTC, stobar93 commented on src/components/Auth/components/Login/Login.tsx
> +  email: Yup.string()
```suggestion
  email: Yup.string().email()
```

2022-04-28 22:10 UTC, stobar93 commented on src/components/Auth/components/Profile/Profile.tsx
> +  const [firstName, setFirstName] = useState("");
Estos estados locales, en donde los estás usando?

2022-04-28 22:10 UTC, stobar93 commented on src/contexts/AuthContext.js
> +  console.log("user: ", user);
Estos console.log los puedes quitar

2022-04-29 04:39 UTC, JustinoTorreblanca commented on src/components/Auth/components/Profile/Profile.tsx
> +  const [firstName, setFirstName] = useState("");
Estaba "hardcodeado" el profile, pero ya obtengo datos de un usuario registrado con supabase

2022-04-29 17:31 UTC, ferpintado approved these changes
Aprobado con unas sugerencias

2022-04-29 17:31 UTC, ferpintado commented on src/components/Auth/components/Login/Login.tsx
> +  const [open, setOpen] = useState(false);
como recomendacion, usar nombres mas significativos, que esta abriendo? openAlert?

2022-04-29 17:31 UTC, ferpintado commented on src/components/Auth/components/Profile/Profile.tsx
> +          {getProfileError ? (
Se podria usar solamente un componente de alerta para evitar duplicacion de codigo, por ejemplo `setAlert` con un objecto `{ type: 'success', message: 'Error message' }`

2022-04-30 23:57 UTC, merged