(UP) Create, delete product
JustinoTorreblanca/dooper-bootcamp pull request #7
Opened 2022-05-15 17:52 UTC by JustinoTorreblanca

https://linear.app/dooper/issue/BOO-35/22-crud-products-ui

2022-05-15 20:25 UTC, sebastobar requested changes

2022-05-15 20:25 UTC, sebastobar commented on pages/admin/products/[product_id].tsx
> +  if (products?.length !== 0) {
Aquí puedes usar el isSuccess de react-query. También me parece que el componente CustomAlert no se renderiza ya que le falta el return

2022-05-15 20:25 UTC, sebastobar commented on pages/admin/products/[product_id].tsx
> +  const [{ title, description, image, price, id }] = products;
Esta interface está definida como un objeto de un solo producto. Me parece que la declaración del array no es necesaria
```
const {title, description, image, price, id} = products
```

2022-05-15 20:25 UTC, sebastobar commented on pages/admin/products/[product_id].tsx
> +    await router.reload();
Si este reload es para ver que sí se eliminó el producto, lo puedes evitar  usando invalidateQueries en el Hook useProducts, tal como lo tienes

2022-05-15 20:25 UTC, sebastobar commented on pages/admin/products/[product_id].tsx
> +    const { data, error } = await supabase
Aquí deberías poner la mutación que te retorna el useCRUDProduct, te puede ayudar a manejar el caso en que sea exitoso o haya un error

2022-05-15 20:25 UTC, sebastobar commented on src/components/ProductsWrapper/ProductCard/ProductCard.tsx
> +  product?: Product;
Este product no tendría incluidas las demás props que definiste aquí?

2022-05-15 20:25 UTC, sebastobar commented on src/components/Admin/CreateNewProduct/CreateNewProduct.tsx
> +    setTimeout(() => setNewProductUploadSuccess(false), 4000);
Te sugiero cambiar esta actualización de estado para que se active cuando haya certeza de que la operación fue exitosa o fallida. Si solo esperas a que pasen los 4 segundos es posible que cambies el estado aún si ocurre algo inesperado

2022-05-16 18:28 UTC, ferpintado commented on pages/admin/products/[product_id].tsx
> +    await router.reload();
https://react-query.tanstack.com/guides/query-invalidation

2022-05-16 18:31 UTC, ferpintado commented on src/components/Admin/CreateNewProduct/CreateNewProduct.tsx
> +        {newProductUploadSuccess ? (
puedes usar la propiedad `isSuccess` de `useMutation` para saber si el request fue satisfactorio, https://react-query.tanstack.com/reference/useMutation#_top

2022-05-18 02:54 UTC, JustinoTorreblanca commented on src/components/Admin/CreateNewProduct/CreateNewProduct.tsx
> +        {newProductUploadSuccess ? (
intente aplicar esta propiedad, pero se quedaba en submitting  😔

2026-03-06 17:18 UTC, closed without merging